CREATE TABLE [dbo].[orchard_Orchard_Projections_PropertyRecord] (
    [Id]                    INT            IDENTITY (1, 1) NOT NULL,
    [Category]              NVARCHAR (64)  NULL,
    [Type]                  NVARCHAR (64)  NULL,
    [Description]           NVARCHAR (255) NULL,
    [State]                 NVARCHAR (MAX) NULL,
    [Position]              INT            NULL,
    [LayoutRecord_id]       INT            NULL,
    [ExcludeFromDisplay]    BIT            NULL,
    [CreateLabel]           BIT            NULL,
    [Label]                 NVARCHAR (255) NULL,
    [LinkToContent]         BIT            NULL,
    [CustomizePropertyHtml] BIT            NULL,
    [CustomPropertyTag]     NVARCHAR (64)  NULL,
    [CustomPropertyCss]     NVARCHAR (64)  NULL,
    [CustomizeLabelHtml]    BIT            NULL,
    [CustomLabelTag]        NVARCHAR (64)  NULL,
    [CustomLabelCss]        NVARCHAR (64)  NULL,
    [CustomizeWrapperHtml]  BIT            NULL,
    [CustomWrapperTag]      NVARCHAR (64)  NULL,
    [CustomWrapperCss]      NVARCHAR (64)  NULL,
    [NoResultText]          NVARCHAR (MAX) NULL,
    [ZeroIsEmpty]           BIT            NULL,
    [HideEmpty]             BIT            NULL,
    [RewriteOutput]         BIT            NULL,
    [RewriteText]           NVARCHAR (MAX) NULL,
    [StripHtmlTags]         BIT            NULL,
    [TrimLength]            BIT            NULL,
    [AddEllipsis]           BIT            NULL,
    [MaxLength]             INT            NULL,
    [TrimOnWordBoundary]    BIT            NULL,
    [PreserveLines]         BIT            NULL,
    [TrimWhiteSpace]        BIT            NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

